In [5]:
# Educational Data Analysis with python

##Notebook 1: Data Loading and Dataset Exploration

#Author:** Kelechi Frank

##Objective

#The purpose of this notebook is to load the dataset, inspect its structure, identify the variables it contains, and understand its overall quality before performing any data cleaning or analysis

In [6]:
import pandas as pd
import numpy as np

In [11]:
#load the dataset
df = pd.read_csv("../datasets.gitkeep/Education_Student_Depression.csv") #go up one folder  to the main project folder
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33,Visakhapatnam,Student,5,0,8.97,2,0,5-6 hours,Healthy,B.Pharm,Yes,3,1.0,No,1
1,8,Female,24,Bangalore,Student,2,0,5.90,5,0,5-6 hours,Moderate,BSc,No,3,2.0,Yes,0
2,26,Male,31,Srinagar,Student,3,0,7.03,5,0,Less than 5 hours,Healthy,BA,No,9,1.0,Yes,0
3,30,Female,28,Varanasi,Student,3,0,5.59,2,0,7-8 hours,Moderate,BCA,Yes,4,5.0,Yes,1
4,32,Female,25,Jaipur,Student,4,0,8.13,3,0,5-6 hours,Moderate,M.Tech,Yes,1,1.0,No,0

In [ ]:
### Observation

The first five rows provide an overview of the dataset. They confirm that the dataset was loaded successfully and allow us to preview the variables that will be analyzed.

In [12]:
#check the size of the dataset
df.shape

(27901, 18)

In [ ]:
### Observation

#The dataset contains **_____ rows** and **_____ columns**, indicating the number of student records and variables available for analysis.

In [13]:
#view column names
df.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

In [14]:
#get information about the dataset
df.info

<bound method DataFrame.info of            id  Gender  Age           City Profession  Academic Pressure  \
0           2    Male   33  Visakhapatnam    Student                  5
1           8  Female   24      Bangalore    Student                  2
2          26    Male   31       Srinagar    Student                  3
3          30  Female   28       Varanasi    Student                  3
4          32  Female   25         Jaipur    Student                  4
...       ...     ...  ...            ...        ...                ...
27896  140685  Female   27          Surat    Student                  5
27897  140686    Male   27       Ludhiana    Student                  2
27898  140689    Male   31      Faridabad    Student                  3
27899  140690  Female   18       Ludhiana    Student                  5
27900  140699    Male   27          Patna    Student                  4

       Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0                  0  8.97                   2                 0
1                  0  5.90                   5                 0
2                  0  7.03                   5                 0
3                  0  5.59                   2                 0
4                  0  8.13                   3                 0
...              ...   ...                 ...               ...
27896              0  5.75                   5                 0
27897              0  9.40                   3                 0
27898              0  6.61                   4                 0
27899              0  6.88                   2                 0
27900              0  9.24                   1                 0

          Sleep Duration Dietary Habits    Degree  \
0              5-6 hours        Healthy   B.Pharm
1              5-6 hours       Moderate       BSc
2      Less than 5 hours        Healthy        BA
3              7-8 hours       Moderate       BCA
4              5-6 hours       Moderate    M.Tech
...                  ...            ...       ...
27896          5-6 hours      Unhealthy  Class 12
27897  Less than 5 hours        Healthy       MSc
27898          5-6 hours      Unhealthy        MD
27899  Less than 5 hours        Healthy  Class 12
27900  Less than 5 hours        Healthy       BCA

      Have you ever had suicidal thoughts ?  Work/Study Hours  \
0                                       Yes                 3
1                                        No                 3
2                                        No                 9
3                                       Yes                 4
4                                       Yes                 1
...                                     ...               ...
27896                                   Yes                 7
27897                                    No                 0
27898                                    No                12
27899                                   Yes                10
27900                                   Yes                 2

       Financial Stress Family History of Mental Illness  Depression
0                   1.0                               No           1
1                   2.0                              Yes           0
2                   1.0                              Yes           0
3                   5.0                              Yes           1
4                   1.0                               No           0
...                 ...                              ...         ...
27896               1.0                              Yes           0
27897               3.0                              Yes           0
27898               2.0                               No           0
27899               5.0                               No           1
27900               3.0                              Yes           1

[27901 rows x 18 columns]>

In [ ]:
### Observation

#The dataset contains both numerical and categorical variables. The `info()` output also helps identify missing values and confirms the data type of each column.

In [15]:
#summary statistics
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000